# docker-compose.yml
version: '2'
services:
  hastebinServer:
    image: rlister/hastebin
    ports: 
      - "7777:7777"
    network_mode: "host"
    volumes: 
      - /srv/haste/data:/app/data
## http://docs.rancher.com/rancher/v1.5/en/cattle/scheduling/
## Make hastebin only run containers on hosts with a purpose=pastie label
    labels:
      io.rancher.scheduler.affinity:host_label: purpose=paste
