version: '2'
catalog:
  name: "hastebinPasteServer"
  version: "v0.1.0"
  description: "Pastebin like server"
  minimum_rancher_version: v1.0.0
  minimum_rancher_version: v1.1.99
  questions:
    - variable: "hasteListenPort"
      label: "hastebin HTTP Port"
      type: "string"
      required: true
      default: "7777"
      description: Default port that hastebin should listen on.

services:
  hastebinServer:
    scale: 1
