version: '2'
services:
  LoadBalancer:
    scale: 2
    lb_config:
      port_rules:
      - source_port: 80
        target_port: 7777
        service: hastebinServer
#    health_check:
#      port: 42
#      interval: 2000
#      unhealthy_threshold: 3
#      healthy_threshold: 2
#      response_timeout: 2000
