version: '2'
services:
  LoadBalancer:
    scale: 2
    lb_config:
      port_rules:
        - source_port: 80
          target_port: 7777
          service: hastebinPasteServer-HA/hastebinServer
          hostname: pastie.aarnet.net.au
